### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by titolim** [velolabs/lattis_sdk_ios_public#9]
Error message:
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler: .../Pods/LattisSDK/Oval.framework/Modules/Oval.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

Please enabled the Build Libraries for Distribution (BUILD_LIBRARY_FOR_DISTRIBUTION) build setting.

**Comment by kabanishe23** [comment]
@titolim Could you please check with **develop** branch. I'll merge and release that fix if it works for you. Thanks

**Comment by titolim** [comment]
Can you build frameworks to also target x86_64-apple-ios-simulator
It's now only supporting arm.
Thanks

**Comment by kabanishe23** [comment]
@titolim I am sure latest develop branch code contains x86_64 support

**Comment by titolim** [comment]
@kabanishe23 ok it's working now
